name: Deploy ecom-frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t shivarame/ecom_frontend  .

      - name: Publish Image to docker hub
        run: docker push shivarame/ecom_frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull shivarame/ecom_frontend:latest
      - name: Delete old container
        run: docker rm -f ecom-frontend-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name ecom-frontend-container shivarame/ecom_frontend
